use bevy::prelude::*;

pub fn from_name(name: &str) -> Color {
    use bevy::color::palettes::css::*;
    match name.to_uppercase().as_str() {
        "AQUA" => srgba_to_color(&AQUA),
        "BLACK" => srgba_to_color(&BLACK),
        "BLUE" => srgba_to_color(&BLUE),
        "FUCHSIA" => srgba_to_color(&FUCHSIA),
        "GRAY" => srgba_to_color(&GRAY),
        "GREEN" => srgba_to_color(&GREEN),
        "LIME" => srgba_to_color(&LIME),
        "MAROON" => srgba_to_color(&MAROON),
        "NAVY" => srgba_to_color(&NAVY),
        "OLIVE" => srgba_to_color(&OLIVE),
        "PURPLE" => srgba_to_color(&PURPLE),
        "RED" => srgba_to_color(&RED),
        "SILVER" => srgba_to_color(&SILVER),
        "TEAL" => srgba_to_color(&TEAL),
        "WHITE" => srgba_to_color(&WHITE),
        "YELLOW" => srgba_to_color(&YELLOW),
        "ALICE_BLUE" => srgba_to_color(&ALICE_BLUE),
        "ANTIQUE_WHITE" => srgba_to_color(&ANTIQUE_WHITE),
        "AQUAMARINE" => srgba_to_color(&AQUAMARINE),
        "AZURE" => srgba_to_color(&AZURE),
        "BEIGE" => srgba_to_color(&BEIGE),
        "BISQUE" => srgba_to_color(&BISQUE),
        "BLANCHED_ALMOND" => srgba_to_color(&BLANCHED_ALMOND),
        "BLUE_VIOLET" => srgba_to_color(&BLUE_VIOLET),
        "BROWN" => srgba_to_color(&BROWN),
        "BURLYWOOD" => srgba_to_color(&BURLYWOOD),
        "CADET_BLUE" => srgba_to_color(&CADET_BLUE),
        "CHARTREUSE" => srgba_to_color(&CHARTREUSE),
        "CHOCOLATE" => srgba_to_color(&CHOCOLATE),
        "CORAL" => srgba_to_color(&CORAL),
        "CORNFLOWER_BLUE" => srgba_to_color(&CORNFLOWER_BLUE),
        "CORNSILK" => srgba_to_color(&CORNSILK),
        "CRIMSON" => srgba_to_color(&CRIMSON),
        "DARK_BLUE" => srgba_to_color(&DARK_BLUE),
        "DARK_CYAN" => srgba_to_color(&DARK_CYAN),
        "DARK_GOLDENROD" => srgba_to_color(&DARK_GOLDENROD),
        "DARK_GRAY" => srgba_to_color(&DARK_GRAY),
        "DARK_GREEN" => srgba_to_color(&DARK_GREEN),
        "DARK_GREY" => srgba_to_color(&DARK_GREY),
        "DARK_KHAKI" => srgba_to_color(&DARK_KHAKI),
        "DARK_MAGENTA" => srgba_to_color(&DARK_MAGENTA),
        "DARK_OLIVEGREEN" => srgba_to_color(&DARK_OLIVEGREEN),
        "DARK_ORANGE" => srgba_to_color(&DARK_ORANGE),
        "DARK_ORCHID" => srgba_to_color(&DARK_ORCHID),
        "DARK_RED" => srgba_to_color(&DARK_RED),
        "DARK_SALMON" => srgba_to_color(&DARK_SALMON),
        "DARK_SEA_GREEN" => srgba_to_color(&DARK_SEA_GREEN),
        "DARK_SLATE_BLUE" => srgba_to_color(&DARK_SLATE_BLUE),
        "DARK_SLATE_GRAY" => srgba_to_color(&DARK_SLATE_GRAY),
        "DARK_SLATE_GREY" => srgba_to_color(&DARK_SLATE_GREY),
        "DARK_TURQUOISE" => srgba_to_color(&DARK_TURQUOISE),
        "DARK_VIOLET" => srgba_to_color(&DARK_VIOLET),
        "DEEP_PINK" => srgba_to_color(&DEEP_PINK),
        "DEEP_SKY_BLUE" => srgba_to_color(&DEEP_SKY_BLUE),
        "DIM_GRAY" => srgba_to_color(&DIM_GRAY),
        "DIM_GREY" => srgba_to_color(&DIM_GREY),
        "DODGER_BLUE" => srgba_to_color(&DODGER_BLUE),
        "FIRE_BRICK" => srgba_to_color(&FIRE_BRICK),
        "FLORAL_WHITE" => srgba_to_color(&FLORAL_WHITE),
        "FOREST_GREEN" => srgba_to_color(&FOREST_GREEN),
        "GAINSBORO" => srgba_to_color(&GAINSBORO),
        "GHOST_WHITE" => srgba_to_color(&GHOST_WHITE),
        "GOLD" => srgba_to_color(&GOLD),
        "GOLDENROD" => srgba_to_color(&GOLDENROD),
        "GREEN_YELLOW" => srgba_to_color(&GREEN_YELLOW),
        "GREY" => srgba_to_color(&GREY),
        "HONEYDEW" => srgba_to_color(&HONEYDEW),
        "HOT_PINK" => srgba_to_color(&HOT_PINK),
        "INDIAN_RED" => srgba_to_color(&INDIAN_RED),
        "INDIGO" => srgba_to_color(&INDIGO),
        "IVORY" => srgba_to_color(&IVORY),
        "KHAKI" => srgba_to_color(&KHAKI),
        "LAVENDER" => srgba_to_color(&LAVENDER),
        "LAVENDER_BLUSH" => srgba_to_color(&LAVENDER_BLUSH),
        "LAWN_GREEN" => srgba_to_color(&LAWN_GREEN),
        "LEMON_CHIFFON" => srgba_to_color(&LEMON_CHIFFON),
        "LIGHT_BLUE" => srgba_to_color(&LIGHT_BLUE),
        "LIGHT_CORAL" => srgba_to_color(&LIGHT_CORAL),
        "LIGHT_CYAN" => srgba_to_color(&LIGHT_CYAN),
        "LIGHT_GOLDENROD_YELLOW" => srgba_to_color(&LIGHT_GOLDENROD_YELLOW),
        "LIGHT_GRAY" => srgba_to_color(&LIGHT_GRAY),
        "LIGHT_GREEN" => srgba_to_color(&LIGHT_GREEN),
        "LIGHT_GREY" => srgba_to_color(&LIGHT_GREY),
        "LIGHT_PINK" => srgba_to_color(&LIGHT_PINK),
        "LIGHT_SALMON" => srgba_to_color(&LIGHT_SALMON),
        "LIGHT_SEA_GREEN" => srgba_to_color(&LIGHT_SEA_GREEN),
        "LIGHT_SKY_BLUE" => srgba_to_color(&LIGHT_SKY_BLUE),
        "LIGHT_SLATE_GRAY" => srgba_to_color(&LIGHT_SLATE_GRAY),
        "LIGHT_SLATE_GREY" => srgba_to_color(&LIGHT_SLATE_GREY),
        "LIGHT_STEEL_BLUE" => srgba_to_color(&LIGHT_STEEL_BLUE),
        "LIGHT_YELLOW" => srgba_to_color(&LIGHT_YELLOW),
        "LIMEGREEN" => srgba_to_color(&LIMEGREEN),
        "LINEN" => srgba_to_color(&LINEN),
        "MAGENTA" => srgba_to_color(&MAGENTA),
        "MEDIUM_AQUAMARINE" => srgba_to_color(&MEDIUM_AQUAMARINE),
        "MEDIUM_BLUE" => srgba_to_color(&MEDIUM_BLUE),
        "MEDIUM_ORCHID" => srgba_to_color(&MEDIUM_ORCHID),
        "MEDIUM_PURPLE" => srgba_to_color(&MEDIUM_PURPLE),
        "MEDIUM_SEA_GREEN" => srgba_to_color(&MEDIUM_SEA_GREEN),
        "MEDIUM_SLATE_BLUE" => srgba_to_color(&MEDIUM_SLATE_BLUE),
        "MEDIUM_SPRING_GREEN" => srgba_to_color(&MEDIUM_SPRING_GREEN),
        "MEDIUM_TURQUOISE" => srgba_to_color(&MEDIUM_TURQUOISE),
        "MEDIUM_VIOLET_RED" => srgba_to_color(&MEDIUM_VIOLET_RED),
        "MIDNIGHT_BLUE" => srgba_to_color(&MIDNIGHT_BLUE),
        "MINT_CREAM" => srgba_to_color(&MINT_CREAM),
        "MISTY_ROSE" => srgba_to_color(&MISTY_ROSE),
        "MOCCASIN" => srgba_to_color(&MOCCASIN),
        "NAVAJO_WHITE" => srgba_to_color(&NAVAJO_WHITE),
        "OLD_LACE" => srgba_to_color(&OLD_LACE),
        "OLIVE_DRAB" => srgba_to_color(&OLIVE_DRAB),
        "ORANGE" => srgba_to_color(&ORANGE),
        "ORANGE_RED" => srgba_to_color(&ORANGE_RED),
        "ORCHID" => srgba_to_color(&ORCHID),
        "PALE_GOLDENROD" => srgba_to_color(&PALE_GOLDENROD),
        "PALE_GREEN" => srgba_to_color(&PALE_GREEN),
        "PALE_TURQUOISE" => srgba_to_color(&PALE_TURQUOISE),
        "PALE_VIOLETRED" => srgba_to_color(&PALE_VIOLETRED),
        "PAPAYA_WHIP" => srgba_to_color(&PAPAYA_WHIP),
        "PEACHPUFF" => srgba_to_color(&PEACHPUFF),
        "PERU" => srgba_to_color(&PERU),
        "PINK" => srgba_to_color(&PINK),
        "PLUM" => srgba_to_color(&PLUM),
        "POWDER_BLUE" => srgba_to_color(&POWDER_BLUE),
        "REBECCA_PURPLE" => srgba_to_color(&REBECCA_PURPLE),
        "ROSY_BROWN" => srgba_to_color(&ROSY_BROWN),
        "ROYAL_BLUE" => srgba_to_color(&ROYAL_BLUE),
        "SADDLE_BROWN" => srgba_to_color(&SADDLE_BROWN),
        "SALMON" => srgba_to_color(&SALMON),
        "SANDY_BROWN" => srgba_to_color(&SANDY_BROWN),
        "SEA_GREEN" => srgba_to_color(&SEA_GREEN),
        "SEASHELL" => srgba_to_color(&SEASHELL),
        "SIENNA" => srgba_to_color(&SIENNA),
        "SKY_BLUE" => srgba_to_color(&SKY_BLUE),
        "SLATE_BLUE" => srgba_to_color(&SLATE_BLUE),
        "SLATE_GRAY" => srgba_to_color(&SLATE_GRAY),
        "SLATE_GREY" => srgba_to_color(&SLATE_GREY),
        "SNOW" => srgba_to_color(&SNOW),
        "SPRING_GREEN" => srgba_to_color(&SPRING_GREEN),
        "STEEL_BLUE" => srgba_to_color(&STEEL_BLUE),
        "TAN" => srgba_to_color(&TAN),
        "THISTLE" => srgba_to_color(&THISTLE),
        "TOMATO" => srgba_to_color(&TOMATO),
        "TURQUOISE" => srgba_to_color(&TURQUOISE),
        "VIOLET" => srgba_to_color(&VIOLET),
        "WHEAT" => srgba_to_color(&WHEAT),
        "WHITE_SMOKE" => srgba_to_color(&WHITE_SMOKE),
        "YELLOW_GREEN" => srgba_to_color(&YELLOW_GREEN),
        _ => {
            // Hash name to a color
            use std::hash::{DefaultHasher, Hash, Hasher};
            let mut s = DefaultHasher::new();
            name.hash(&mut s);
            let hash: u64 = s.finish();
            let h = u8_to_float((hash & 0xFF) as u8) * 360.0;
            let s = 0.5 + (u8_to_float(((hash >> 8) & 0xFF) as u8) * 0.5);
            let l = 0.3 + (u8_to_float(((hash >> 16) & 0xFF) as u8) * 0.4);
            Color::hsl(h, s, l)
        }
    }
}

fn srgba_to_color(color: &Srgba) -> Color {
    Color::srgb(color.red, color.green, color.blue)
}

fn u8_to_float(c: u8) -> f32 {
    c as f32 / 255.0
}
